include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    library_names: true
    library_prefixes: true
    camel_case_types: true
    constant_identifier_names: true
    #file_names: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    omit_local_variable_types: false
    prefer_final_locals: true
    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    use_full_hex_values_for_flutter_colors: true
    depend_on_referenced_packages: true
    use_build_context_synchronously: true
    always_specify_types: true
    use_super_parameters: true
    no_wildcard_variable_uses: true
    unnecessary_to_list_in_spreads: true
    require_trailing_commas: true
analyzer:
  exclude:
    - lib/model/**
    - lib/generated/**
    - '**/lib/l10n/**'
    - 'lib/l10n/**'
    - '**/*.g.dart'