name: the_office
description: "The Office"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  flame: ^1.37.0
  flame_tiled: ^3.1.1
  flame_audio: ^2.12.1
  vector_math: ^2.2.0
  get_it: ^9.2.1
  clipper2: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
    - assets/fonts/
  shaders:
    - assets/shaders/lighting.frag
  fonts:
    - family: 'PressStart2P'
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
